### ISSUE TITLE
Webstorm can't get svelte configuration information

### ISSUE THREAD

**Issue by Langlw1992** [pchynoweth/svelte-sequential-preprocessor#176]
Hi
  I'm tring to integrate melt-ui into my project, which uses svelte-sequential-preprocessor as preprocess. However, there's a problem with my IDE Webstorm that the configuration in svelte.config.js can't be read and some special path like '$lib' can't be recognized with 'Svelte: Cannot find module  $lib  or its corresponding type declarations.' error.

Hope to get your help

**Comment by pchynoweth** [comment]
I don't use Webstorm and I haven't tried meta-ui, but I can try to help. Can you provide a minimal reproducible example?

I searched around a bit and found this issue. It's a similar issue with vscode. I don't know if any of the suggestions will help you.

https://github.com/sveltejs/language-tools/issues/1459#issuecomment-1207128240
